name: linksubmit

on:
  schedule:
    - cron: '0 0-23/5 * * *'
  workflow_dispatch:
jobs:
  linksubmit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚀
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.4' # The Go version to download (if necessary) and use
      - run: |
          wget https://raw.githubusercontent.com/h7ml/h7ml.github.io/netlify/sitemap.txt -O urls.txt
          go mod download
          go run link.go

  hot_page:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone 🚀
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      - name: Checkout 🚀
        uses: actions/checkout@v2
        with:
          ref: vitepress
          persist-credentials: false
          fetch-depth: 0
      - name: Install pnpm  🚀
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Install dependencies  🚀
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install --no-frozen-lockfile

      - name: Setup Node.js 🚀
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install crawler  🚀
        run: |
          pnpm run crawler:interview
          pnpm run lint

      - name: Commit files 🚀
        run: |
          git add .
          git config --local user.email "h7ml@qq.com"
          git config --local user.name "h7ml"
          git commit --allow-empty -m ":rocket: Update today's hot rank on $(date)" -a
      - name: Push changes 🚀
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: 'vitepress'

      - name: build test  🚀
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn build
