name: 'sync'

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"


jobs:
  gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/h7ml
          dst: gitee/h7ml
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          # static_list: "h7ml"
          force_update: true
          account_type: user
          clone_style: ssh
          black_list: "h7ml.github.io"
          debug: true

#   gitlab:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Mirror the Github organization repos to gitlab.
#         uses: Yikun/hub-mirror-action@master
#         with:
#           src: github/h7ml
#           dst: gitlab/h7ml
#           dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
#           dst_token: ${{ secrets.GITEE_TOKEN }}
#           # static_list: "h7ml"
#           force_update: true
#           account_type: user
#           clone_style: ssh
#           debug: true
